# Generated by Django 4.0.1 on 2022-01-13 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spectrum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='posts',
            field=models.ManyToManyField(blank=True, related_name='posts', to='spectrum.Post'),
        ),
    ]
