# Generated by Django 4.0.1 on 2022-01-13 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spectrum', '0002_interest_posts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='hood',
            new_name='interest',
        ),
    ]
